# Generated by Django 2.2.9 on 2020-01-31 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
